version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.6
  circleci-cli: circleci/circleci-cli@0.1.6
  envsubst-alpha: sawadashota/envsubst@dev:alpha

release_filters: &release_filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

workflows:
  version: 2
  test:
    jobs:
      - orb-tools/lint
      - orb-tools/pack
      - orb-tools/publish-dev:
          context: circleci
          requires:
            - orb-tools/pack
          orb-name: sawadashota/envsubst
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
      - orb-tools/trigger-integration-workflow
      - orb-tools/test-in-builds:
          requires:
            - orb-tools/publish-dev
          orb-name: envsubst-alpha
          attach-workspace: true
          test-steps:
            - envsubst-alpha/install
            - run:
                name: Assert installed directory
                command: |
                  which envsubst && test $(which envsubst) = "/usr/local/bin/envsubst"

  release:
    jobs:
      - orb-tools/pack:
          filters: *release_filters
      - orb-tools/publish:
          filters: *release_filters
          context: circleci
          requires:
            - orb-tools/pack
          orb-ref: sawadashota/envsubst@${CIRCLE_TAG}
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
