version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.6
  circleci-cli: circleci/circleci-cli@0.1.6
  envsubst-alpha: sawadashota/envsubst@dev:alpha

workflows:
  version: 2
  test:
    jobs:
      - orb-tools/pack
      - orb-tools/publish-dev:
          context: circleci
          requires:
            - orb-tools/pack
          orb-name: sawadashota/envsubst
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
      - orb-tools/test-in-builds:
          requires:
            - orb-tools/pack
          orb-name: sawadashota/envsubst
          attach-workspace: true
          test-steps:
            - envsubst-alpha/install
            - run: envsubst --version

  release:
    jobs:
      - orb-tools/pack:
          filters: &release_filter
            tags:
              only: /.*/
            branches:
              ignore: /.*/
      - orb-tools/publish:
          filters: *release_filter
          context: circleci
          requires:
            - orb-tools/pack
          orb-ref: sawadashota/envsubst@${CIRCLE_TAG}
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
