version: 2.1

orbs:
  orb-tools: circleci/orb-tools@12.0
  # For test
  envsubst-alpha: sawadashota/envsubst@dev:alpha

parameters:
  run-integration-tests:
    type: boolean
    default: false
  dev-orb-version:
    type: string
    default: "dev:alpha"

release_filters: &release_filters
  branches:
    ignore: /.*/
  tags:
    only: /[0-9]+\.[0-9]+\.[0-9]+/

workflows:
  version: 2
  dev:
    unless: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/lint:
          name: lint-dev
      - orb-tools/pack:
          name: pack-dev
      - orb-tools/publish:
          name: publish-dev
          context: orb-publishing
          requires: [pack-dev]
          orb_name: sawadashota/envsubst
          checkout: false
          vcs_type: <<pipeline.project.type>>
      - orb-tools/trigger-integration-tests-workflow:
          name: trigger-integration-workflow-dev
          context: orb-publishing
          requires: [publish-dev]

  integration_dev:
    when: << pipeline.parameters.run-integration-tests >>
    jobs:
      - orb-tools/pack:
          name: pack-integration_dev
      - orb-tools/test-in-builds:
          name: test-in-builds-integration_dev
          requires: [pack-integration_dev]
          orb-name: envsubst-alpha
          attach-workspace: true
          test-steps:
            - envsubst-alpha/install
            - run:
                name: Assert installed directory
                command: which envsubst && test $(which envsubst) = "/usr/local/bin/envsubst"

  production:
    jobs:
      - orb-tools/pack:
          name: pack-production
          filters: *release_filters
      - orb-tools/publish:
          name: publish-production
          filters: *release_filters
          context: orb-publishing
          requires: [pack-production]
          orb-ref: sawadashota/envsubst@${CIRCLE_TAG}
          pub-type: production
          checkout: false
          vcs_type: <<pipeline.project.type>>
