version: 2.1

orbs:
  orb-tools: circleci/orb-tools@8.27.6
  circleci-cli: circleci/circleci-cli@0.1.6
  envsubst-alpha: sawadashota/envsubst@dev:alpha

release_filters: &release_filters
  tags:
    only: /.*/
  branches:
    ignore: /.*/

workflows:
  version: 2
  dev:
    jobs:
      - orb-tools/lint:
          name: lint-dev
      - orb-tools/pack:
          name: pack-dev
      - orb-tools/publish-dev:
          name: publish-dev
          context: circleci
          requires: [pack-dev]
          orb-name: sawadashota/envsubst
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
      - orb-tools/trigger-integration-workflow:
          name: trigger-integration-workflow-dev
          context: circleci
          requires: [publish-dev]
      - orb-tools/test-in-builds:
          requires: [trigger-integration-workflow-dev]
          orb-name: envsubst-alpha
          attach-workspace: true
          test-steps:
            - envsubst-alpha/install
            - run:
                name: Assert installed directory
                command: which envsubst && test $(which envsubst) = "/usr/local/bin/envsubst"

  production:
    jobs:
      - orb-tools/pack:
          name: pack-production
          filters: *release_filters
      - orb-tools/publish:
          name: publish-production
          filters: *release_filters
          context: circleci
          requires: [pack-production]
          orb-ref: sawadashota/envsubst@${CIRCLE_TAG}
          publish-token-variable: CIRCLE_TOKEN
          validate: true
          checkout: false
          attach-workspace: true
